### PR TITLE
Retry failed checkouts

### LINKED ISSUE #477: Retry/sleep Git checkouts
Sometimes GitHub web hooks sender faster than the time it takes for their Git servers to update. So builds end up starting before the commit exists.

This often surfaces as this error:

```
$ git checkout -f <hash>
fatal: reference is not a tree: <hash>
```

It would be good if the agent could "guess" if the checkout failed because of this, and do an automatic sleep/retry (with a sensible "give up" limit).

This should be pretty straight forward since we moved the Bootstrap to "Golang" - we already have a `retry` package that can help here too.

### PR DESCRIPTION
**Pull request by lox**
@keithpitt finally convinced me that we should be doing checkout retries by default. 

Closes #477.

### CODE REVIEW

File: bootstrap/bootstrap.go [hunk 1]
```diff
@@ -599,21 +594,15 @@ func (b *Bootstrap) CheckoutPhase() error {
...
 			if err != nil {
-				return err
-			}
-		} else {
-			if err := doCheckout(); err != nil {
-				return err
+				b.shell.Warningf("%s (%s)", err, s)
 			}
+			return err
+		}, &retry.Config{Maximum: 10, Interval: 5 * time.Second})
```
Comment (keithpitt) [inline bootstrap/bootstrap.go]: Tweak values here
