### PR TITLE
Fix regression in pipeline upload with no-interpolation

### LINKED ISSUE #3358: Regression in `buildkite-agent` v3.99.0 with `--no-interpolation` and step `key`
## Summary

Starting from Buildkite Agent version **3.99.0**, using `--no-interpolation` with nested pipeline uploads fails when a step defines a `key`, even though the parent pipeline does not reuse the key itself.

### Error

```bash
buildkite-agent: fatal: Failed to upload and process pipeline: Pipeline upload rejected: The key "test-key" has already been used by another step in this build
```

This appears to be a regression, as previous versions allowed such nested uploads without complaint.

---

## 🔁 Reproduction Steps

Given the following pipeline structure:

### 1. Initial pipeline uploaded via UI

```yaml
steps:
  - label: "testing"
    command:
      - buildkite-agent pipeline upload test-pipeline.yml
```

### 2. `test-pipeline.yml`

```yaml
steps:
  - label: "testing"
    command: buildkite-agent pipeline upload test-pipeline-uploaded.yml --no-interpolation
```

### 3. `test-pipeline-uploaded.yml`

```yaml
steps:
  - label: "testing"
    key: "test-key"
    command:
      - echo hello world
```

This results in the following failure in v3.99.0:

Error Screenshot

---

## ✅ Expected Behavior

The nested `pipeline upload` should succeed as long as no two steps within the *same final flattened pipeline* reuse the same key. In this case, only one step uses the `key: test-key`.

This behavior worked in previous versions of the agent, and pipelines depending on this now fail after upgrading to v3.99.0.

---

## 📌 Notes

- The issue only happens when using `--no-interpolation`.

### PR DESCRIPTION
**Pull request by DrJosh9000**
### Description

When interpolation was disabled, a pipeline would be uploaded twice.

### Context

Fixes #3358 

### Changes

- Fix the bug
- Add new test
- Make all the other tests check outputs as a whole

### Testing
- [x] Tests have run locally (with `go test ./...`). Buildkite employees may check this if the pipeline has run automatically.
- [x] Code is formatted (with `go fmt ./...`)

### CODE REVIEW

File: clicommand/pipeline_upload.go [hunk 1]
```diff
@@ -552,12 +552,14 @@ func (cfg *PipelineUploadConfig) parseAndInterpolate(ctx context.Context, src st
 				if !yield(nil, fmt.Errorf("pipeline parsing of %q failed: %w", src, err)) {
 					return
 				}
+				continue
```
Comment (wolfeidau) [inline clicommand/pipeline_upload.go]: should this refactored into a switch?

**Review by wolfeidau — CHANGES_REQUESTED** [review]
Just one suggestion, i find all the continues are a sign of maybe needing a switch statement?

File: clicommand/pipeline_upload.go (hunk 1 above)
Comment (DrJosh9000) [reply clicommand/pipeline_upload.go]: Done.

**Review by wolfeidau — APPROVED** [review]
👍🏻 🚀
