### PR TITLE
Avoid destroying the checkout on specific git errors

### LINKED ISSUE #1088: fatal: reference is not a tree [commit] is causing re-download of entire repository
May be similar to #581

- Pushing directly to staging branch.
- Staging has been protected previously in GitHub, but disabling this didn't help.
- Agent is deleting and re-downloading the entire repo on a checkout error - not all the time but very frequently.
- This is blowing out build times from 3 to 15 minutes, as every step needs to re-download the repo.
- An old PR is referenced in the messages and buildkite, which was long closed and merged.
- The difference between the below simple step with and without re-checkout is 3m31s vs 11s.
- See in below log comments with ###
- Some information is redacted.

`buildkite-agent pipeline upload .buildkite/pipeline.yaml`

```
~~~ Running global environment hook
[90m$[0m buildkite/hooks/environment
--- :house_with_garden: Setting up the environment

[90m# BUILDKITE_DISABLE_GIT_SUBMODULES changed[0m
[90m# BUILDKITE_NO_GIT_SUBMODULES changed[0m
[90m# BUILDKITE_GIT_SUBMODULES changed[0m   ### Dont think any of these even work?
~~~ Preparing working directory
[90m$[0m cd /buildkite/builds/general-buildkite-agent-1-1/base-up/platform
[90m# Host "github.com" already in list of known hosts at "/root/.ssh/known_hosts"[0m
[90m$[0m git remote set-url origin git@github.com:base-up/platform.git
[90m$[0m git submodule foreach --recursive "git clean -ffxdq"

Entering [SUBMODULE]  ### REDACTED - message appears for all submodules

[90m$[0m git clean -ffxdq
[90m# Fetch and checkout pull request head from GitHub[0m
[90m$[0m git fetch -v --prune origin refs/pull/297/head ### Why is this being fetched? PR was closed on 1 Aug.
key_load_public: invalid format                         ### AFAIK, not an issue.

From github.com:base-up/platform

 * branch                refs/pull/297/head -> FETCH_HEAD

[90m# FETCH_HEAD is now `4a4cb804523e6692b29a65546401b307ab60b77b`[0m     ### Incorrect and unrelated closed PR commit
[90m$[0m git checkout -f 51e271f13b7d676a5989a37084bdeb5b2c0fab62         ### Correct commit reference
fatal: reference is not a tree: 51e271f13b7d676a5989a37084bdeb5b2c0fab62

[33m⚠️ Warning: Checkout failed! exit status 128 (Attempt 1/3 Retrying in 2s)[0m       ### Presumably because we're now on the PR branch?
^^^ +++
[90m# Removing /buildkite/builds/general-buildkite-agent-1-1/base-up/platform[0m       ### Now the entire repo needs re-downloading.
[90m# Host "github.com" already in list of known hosts at "/root/.ssh/known_hosts"[0m
[90m# Creating "/buildkite/builds/general-buildkite-agent-1-1/base-up/platform"[0m
[90m$[0m git clone -v -- git@github.com:base-up/platform.git .
Cloning into '.'...

key_load_public: invalid format

### Long download for whole repo....

[90m$[0m git submodule foreach --recursive "git clean -ffxdq"
[90m$[0m git clean -ffxdq
[90m# Fetch and checkout pull request head from GitHub[0m
[90m$[0m git fetch -v --prune origin refs/pull/297/head       ### Once again with the unrelated PR?
key_load_public: invalid format

From github.com:base-up/platform

 * branch                refs/pull/297/head -> FETCH_HEAD

[90m# FETCH_HEAD is now `4a4cb804523e6692b29a65546401b307ab60b77b`[0m     ### Again incorrect and unrelated closed pr commit
[90m$[0m git checkout -f 51e271f13b7d676a5989a37084bdeb5b2c0fab62         ### Correct commit reference
Note: checking out '51e271f13b7d676a5989a37084bdeb5b2c0fab62'.



You are in 'detached HEAD' state. You can look around, make experimental

changes and commit them, and you can discard any commits you make in this

state without impacting any branches by performing another checkout.



If you want to create a new branch to retain commits you create, you may

do so (now or later) by using -b with the checkout command again. Example:



  git checkout -b <new-branch-name>



HEAD is now at 51e271f13 [REDACTED]                                     ### Got the commit fine this time...

[90m# Git submodules detected[0m
[90m$[0m git submodule sync --recursive
[90m$[0m git submodule update --init --recursive --force

[REDACTED] ### Submodule downloads

[90m# Checking to see if Git data needs to be sent to Buildkite[0m
[90m$[0m buildkite-agent meta-data exists buildkite:git:commit
[90m# Sending Git commit information back to Buildkite[0m
[90m$[0m buildkite-agent meta-data set buildkite:git:commit "commit 51e271f13b7d676a5989a37084bdeb5b2c0fab62 [REDACTED]"
~~~ Running global pre-command hook
[90m$[0m /buildkite/hooks/pre-command
--- :wrench: Configuring bazel for CI environment

~~~ Running commands
[90m$[0m buildkite-agent pipeline upload .buildkite/pipeline.yaml
[38;5;48m2019-09-17 12:03:32 INFO  [0m [0mReading pipeline config from ".buildkite/pipeline.yaml"[0m

[38;5;48m2019-09-17 12:03:32 INFO  [0m [0mUpdating BUILDKITE_COMMIT to "51e271f13b7d676a5989a37084bdeb5b2c0fab62"[0m

[38;5;48m2019-09-17 12:03:33 INFO  [0m [0mSuccessfully uploaded and parsed pipeline config[0m
```

### PR DESCRIPTION
**Pull request by lox**
This avoids destroying the build working directory on certain errors, including git checkout failures. Re-clones can be expensive! 

Closes #1088.

### CODE REVIEW

File: bootstrap/bootstrap.go [hunk 1]
```diff
@@ -1157,11 +1171,11 @@ func (b *Bootstrap) defaultCheckoutPhase() error {
 	}
 
 	if b.Commit == "HEAD" {
-		if err := b.shell.Run("git", "checkout", "-f", "FETCH_HEAD"); err != nil {
+		if err := gitCheckout(b.shell, `-f`, `FETCH_HEAD`); err != nil {
```
Comment (keithpitt) [inline bootstrap/bootstrap.go]: Out of interest, what's up with the new ` party? Are they better?

Comment (lox) [reply bootstrap/bootstrap.go]: @keithpitt I use `` for literals.

Comment (petemounce) [inline bootstrap/bootstrap.go]: It can expose intent more to write out the long-form flags when shelling out to things; they're more revealing and more searchable in docs.

IMO short-form requires more knowledge of the reader, and are only really a when-typing optimisation - and even then, not really, because one still has to remember what they're for since they're in shell history now.
