### PR TITLE
Don’t override the command exit code when artifact_paths also fails

### LINKED ISSUE #1099: Artifact upload failure overrides command exit code
Sequence of events:

1. A command failure with exit code 255 which we wanted to retry
2. Artifact upload failed with exit 1
3. Retry logic did not execute because the exit code is now 1

Logs (with some truncation)
```
- Running docker-compose --project-name dd442944-68a0-47e8-802c-dce44d3907d4 --file .buildkite/docker-compose.yml down 2>&1
--
  | Couldn't connect to Docker daemon at http+docker://localhost - is it running?
  | 🚨 Error: The command exited with status 255
  | Uploading artifacts | 57s
  | $ buildkite-agent artifact upload log/*.log;tmp/results/*;tmp/capybara/*;tmp/spec_output/**/*;coverage/*json;individual_knapsack_*;rspec_json_results_*
  | 2019-10-03 09:27:28 INFO   Found 5 files that match "log/*.log;tmp/results/*;tmp/capybara/*;tmp/spec_output/**/*;coverage/*json;individual_knapsack_*;rspec_json_results_*"
  | 2019-10-03 09:27:28 INFO   Creating (0-5)/5 artifacts
  | 2019-10-03 09:27:29 INFO   Uploading artifact 95c651ee-1da3-48f3-8016-bb7e1691c3b9 rspec_json_results_rspec_40.json (0 bytes)
  | 2019-10-03 09:27:29 INFO   Uploading artifact d49d9dd6-4046-4018-9f66-9e4767ef6db1 log/active_job.log (21729 bytes)
  | 2019-10-03 09:27:29 INFO   Uploading artifact f1edd13e-efbf-48ed-ad00-e808ba53e14a log/webpack.log (0 bytes)
  | 2019-10-03 09:27:29 INFO   Uploading artifact 318581ce-7320-4763-8bbb-04dfebdcdfb0 log/test.log (331310 bytes)
  | 2019-10-03 09:27:29 INFO   Uploading artifact 288e80dc-7d5e-44b2-a871-63c0a21abea8 log/vcr-38.log (0 bytes)
  | 2019-10-03 09:27:29 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=336831 with Body length 337491 (Attempt 1/10 Retrying in 5s)
  | 2019-10-03 09:27:35 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=340791 with Body length 341121 (Attempt 2/10 Retrying in 5s)
  | 2019-10-03 09:27:40 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=345411 with Body length 345741 (Attempt 3/10 Retrying in 5s)
  | 2019-10-03 09:27:45 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=349701 with Body length 350031 (Attempt 4/10 Retrying in 5s)
  | 2019-10-03 09:27:51 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=371322 with Body length 376934 (Attempt 5/10 Retrying in 5s)
  | 2019-10-03 09:27:57 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=406926 with Body length 410274 (Attempt 6/10 Retrying in 5s)
  | 2019-10-03 09:28:02 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=427470 with Body length 428716 (Attempt 7/10 Retrying in 5s)
  | 2019-10-03 09:28:08 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=441129 with Body length 448038 (Attempt 8/10 Retrying in 5s)
  | 2019-10-03 09:28:13 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=477494 with Body length 477949 (Attempt 9/10 Retrying in 5s)
  | 2019-10-03 09:28:19 WARN   Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=510522 with Body length 514786 (Attempt 10/10 Retrying in 5s)
  | 2019-10-03 09:28:24 ERROR  Error uploading artifact "log/test.log": Post https://s3.amazonaws.com/buildkiteartifacts.com: net/http: HTTP/1.x transport connection broken: http: ContentLength=510522 with Body length 514786
  | 2019-10-03 09:28:25 FATAL  Failed to upload artifacts: There were errors with uploading some of the artifacts
  | 🚨 Error: exit status 1
```

### PR DESCRIPTION
**Pull request by keithduncan**
Whether the command errors or not, we always attempt to upload the artifact paths indicated in the `artifact_paths` command step property.

While we discussed only attempting an upload following a successful command (and phase) execution, changing this would be a backwards incompatible change. Instead, we decided to bypass the artifact exit code reporting when _both_ command and artifact upload errored. We still eventually exit with a non-zero code, but we preserve the command’s exit code so that any automatic retry attributes are applied.

Fixes #1099

### CODE REVIEW

File: bootstrap/bootstrap.go [hunk 1]
```diff
@@ -160,6 +160,22 @@ func (b *Bootstrap) Run(ctx context.Context) (exitCode int) {
 	if phaseErr == nil && includePhase(`command`) {
 		var commandErr error
 		phaseErr, commandErr = b.CommandPhase(ctx)
+		/*
+			Five possible states at this point:
+
+			Pre-command failed
+			Pre-command succeeded, command failed, post-command succeeded
```
Comment (keithduncan) [inline bootstrap/bootstrap.go:167]: This change only affects this case, if the post-command succeeds there is no `phaseError` to report.

File: bootstrap/bootstrap.go [hunk 2]
```diff
@@ -160,6 +160,22 @@ func (b *Bootstrap) Run(ctx context.Context) (exitCode int) {
...
+			Pre-command succeeded, command failed, post-command failed
```
Comment (keithduncan) [inline bootstrap/bootstrap.go:168]: In this case the post-command `phaseError` will be reported and the command exit code _will not be reported_.

That may be a change we want to make, but this pull request does not change that behaviour at this time.
