### PR TITLE
Fix some common artifact download bugs

### LINKED ISSUE #2774: Downloading multiple artifacts with the same file name corrupts them.
We've recently diagnosed a situation where artifacts appeared to be getting corrupted and discovered it's when multiple are created with the same name in different steps, then downloaded to a final step.

eg. 

Step 1:    Uploads artifacts:
 *   package_amd64.deb
 *   package_all.deb

Step 2:    Uploads artifacts:
 *   package_arm64.deb
 *   package_all.deb

Step 3:   Downloads all artifacts from step 1 and 2: 
 *   package_amd64.deb
 *   package_arm64.deb
 *   package_all.deb    <-  will be corrupted combination of the two.

This took a while to diagnose because the corrupted file is the correct size and because it's a mixing of two similar files (in our case they were supposedly identical but because some file date stamps were different, the compressed content was unusable).

The buildkite agent code that downloads artifacts from S3 appears to grab a list of all artifacts and downloads them in parallel, it looks likely that this is where the problem happens.

I realise creating multiple artifacts with the same name is not recommended, but it's a very easy mistake to make.

Is it possible to either fix this behaviour or at least make it clearer in the documentation that this is an easy to make mistake.

### PR DESCRIPTION
**Pull request by DrJosh9000**
### Description

While investigating the artifact download process a bit more, I discovered some fairly low-hanging fruit in the existing downloader.

### Context

Fixes #2774 by making one or another artifact the "winner", and printing a SHA256 sum of the content that it downloaded.

https://coda.io/d/_dHnUHNps1YO#View-3-of-Escalations-Table_tu3KF/r437&view=modal

### Changes

- Write to a temp file and move it to the destination name when ready
- Check the error return from Close
- Print a SHA256 sum of the content
- Add ability to verify SHA256 checksum (not yet used)
- Make error strings more Gothic

### Testing
- [x] Tests have run locally (with `go test ./...`). Buildkite employees may check this if the pipeline has run automatically.
- [x] Code is formatted (with `go fmt ./...`)

### CODE REVIEW

File: agent/download.go [hunk 1]
```diff
@@ -158,23 +163,47 @@ func (d Download) try(ctx context.Context) error {
...
+	// On Unix-like platforms this is generally an "atomic replace".
+	// Caveats: https://pkg.go.dev/os#Rename
+	if err := os.Rename(temp.Name(), targetPath); err != nil {
+		return fmt.Errorf("renaming temp file to target (%T: %w)", err, err)
+	}
+
+	gotSHA256 := hex.EncodeToString(hash.Sum(nil))
+
+	// If the downloader was configured with a checksum to check, check it
+	if d.conf.WantSHA256 != "" && gotSHA256 != d.conf.WantSHA256 {
```
Comment (wolfeidau) [inline agent/download.go:202]: Should the verification happen before you move the file?

**Review by wolfeidau — CHANGES_REQUESTED** [review]
Just one query.

File: agent/download.go (hunk 1 above)
Comment (DrJosh9000) [reply agent/download.go:202]: Yes, it should! Good pickup.

**Review by wolfeidau — APPROVED** [review]

**Comment by jim-barber-he** [comment]
This change has resulted in permissions changes of the artifacts where group and world permissions bits are lost/gone.
It used to use `os.Create` with combine 0666 with the UMASK, while `os.CreateTemp` will lock permissions down since temporary files are only accessible by the user creating them.

This caused an outage for us because our application build doesn't make sure the files have appropriate permissions on them.
See:
https://forum.buildkite.community/t/permissions-on-artifacts-changed-with-version-3-75-0-of-buildkite-agent/3803

**Comment by DrJosh9000** [comment]
Thanks for pointing this out @jim-barber-he, the permissions change was definitely unintentional. #2894 to fix it should be in the next release.
