### PR TITLE
Fix bug where disconnect-after-idle stopped working

### LINKED ISSUE #1003: Agent not terminating with disconnect-after-idle-out anymore
Just downloaded newest release 3.11.3 for testing.

Looks like the agent isn't terminating after the idle period has elapsed...?

See systemctl status for latest updates from agent:
```
[ec2-user@ip-10-69-8-84 ~]$ sudo systemctl status buildkite-agent -l
● buildkite-agent.service - Buildkite Agent
   Loaded: loaded (/etc/systemd/system/buildkite-agent.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/buildkite-agent.service.d
           └─10-power-off-stop.conf
   Active: active (running) since Wed 2019-05-08 03:31:41 UTC; 40min ago
     Docs: https://buildkite.com/agent
 Main PID: 5104 (buildkite-agent)
    Tasks: 9
   Memory: 22.1M
   CGroup: /system.slice/buildkite-agent.service
           └─5104 /usr/bin/buildkite-agent start

May 08 03:31:44 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:44 INFO   Registering agent 1 of 2 with Buildkite...
May 08 03:31:44 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:44 INFO   Registering agent 2 of 2 with Buildkite...
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   Started 2 Agent(s)
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   You can press Ctrl-C to stop the agents
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   sharedservices-dummy-au.linux-i-0cd5f0302963566ca-2 Connecting to Buildkite...
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   sharedservices-dummy-au.linux-i-0cd5f0302963566ca-1 Connecting to Buildkite...
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   sharedservices-dummy-au.linux-i-0cd5f0302963566ca-1 Waiting for job to be assigned...
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   sharedservices-dummy-au.linux-i-0cd5f0302963566ca-1 The agent will automaticallydisconnect after 1800 seconds of inactivity
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   sharedservices-dummy-au.linux-i-0cd5f0302963566ca-2 Waiting for job to be assigned...
May 08 03:31:45 ip-10-69-8-84.sharedservices.dummy.au.aws buildkite-agent[5104]: 2019-05-08 03:31:45 INFO   sharedservices-dummy-au.linux-i-0cd5f0302963566ca-2 The agent will automaticallydisconnect after 1800 seconds of inactivity
```

Date command ran after more than 1800 seconds have elapsed and no activity on my agents.
```
[ec2-user@ip-10-69-8-84 ~]$ date
Wed May  8 04:11:53 UTC 2019
```

Could be something I've misconfigured potentially? Or there has been a bug introduced by https://github.com/buildkite/agent/issues/985, what you think @lox

### PR DESCRIPTION
**Pull request by lox**
We introduced a bug in #985 where the wrong return param from the register API was checked and the idle monitor never detected all the agents idle.

Closes #1003.

### CODE REVIEW

**Comment by lox** [comment]
This needs a test, but it's tough to test, so going to get a fix out first.

File: agent/agent_worker.go [hunk 1]
```diff
@@ -485,7 +485,7 @@ func (a *AgentWorker) Ping() {
 	if a.agentConfiguration.DisconnectAfterIdleTimeout > 0 {
 		a.logger.Info("Job finished. Resetting idle timer...")
 		a.idleTimer.Reset(time.Second * time.Duration(a.agentConfiguration.DisconnectAfterIdleTimeout))
-		a.idleMonitor.MarkBusy(a.agent.Name)
+		a.idleMonitor.MarkBusy(a.agent.UUID)
```
Comment (lox) [inline agent/agent_worker.go]: 🤦🏼‍♂️

Comment (lucas044) [reply agent/agent_worker.go]: :joy: nice one
